knife client delete pluto-elasticsearch-acceptance-0 -y
knife client delete pluto-elasticsearch-production-0 -y
knife client delete pluto-jenkins-management-0 -y
knife client delete pluto-jfrog-management-0 -y
knife client delete pluto-maven-management-0 -y
knife client delete pluto-mysql-acceptance-0 -y
knife client delete pluto-mysql-production-0 -y
knife client delete pluto-redis-acceptance-0 -y
knife client delete pluto-redis-production-0 -y
knife client delete pluto-sensu-management-0 -y
knife client delete pluto-splunk-management-0 -y
knife client delete pluto-tomcat-acceptance-0 -y
knife client delete pluto-tomcat-acceptance-1 -y
knife client delete pluto-tomcat-production-0 -y
knife client delete pluto-tomcat-production-1 -y
knife node delete pluto-elasticsearch-acceptance-0 -y
knife node delete pluto-elasticsearch-production-0 -y
knife node delete pluto-jenkins-management-0 -y
knife node delete pluto-jfrog-management-0 -y
knife node delete pluto-maven-management-0 -y
knife node delete pluto-mysql-acceptance-0 -y
knife node delete pluto-mysql-production-0 -y
knife node delete pluto-redis-acceptance-0 -y
knife node delete pluto-redis-production-0 -y
knife node delete pluto-sensu-management-0 -y
knife node delete pluto-splunk-management-0 -y
knife node delete pluto-tomcat-acceptance-0 -y
knife node delete pluto-tomcat-production-0 -y
knife node delete pluto-tomcat-production-1 -y
knife node delete pluto-tomcat-acceptance-1 -y
